version: '3.1'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: gamification-db
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
    volumes:
      - ./mongo:/data/db